apiVersion: v1
kind: Service
metadata:
  name: {{ include "pesitwizard-server.fullname" . }}
  labels:
    {{- include "pesitwizard-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pesitPort }}
      targetPort: pesit
      protocol: TCP
      name: pesit
    {{- if .Values.service.pesitTlsPort }}
    - port: {{ .Values.service.pesitTlsPort }}
      targetPort: {{ .Values.service.pesitTlsPort }}
      protocol: TCP
      name: pesit-tls
    {{- end }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pesitwizard-server.selectorLabels" . | nindent 4 }}
