apiVersion: v2
name: pesitwizard-client
description: PeSIT Wizard Client - PeSIT file transfer client with web UI
type: application
version: 0.0.0-dev
appVersion: "1.2.2-SNAPSHOT"
keywords:
  - pesitwizard
  - pesit
  - file-transfer
  - client
maintainers:
  - name: PeSIT Wizard Team
