apiVersion: v2
name: pesitwizard-server
description: PeSIT Wizard Server - PeSIT file transfer server (standalone mode)
type: application
version: 0.0.0-dev
appVersion: "1.2.0-SNAPSHOT"
keywords:
  - pesitwizard
  - pesit
  - file-transfer
  - server
maintainers:
  - name: PeSIT Wizard Team
