apiVersion: v2
name: pesitwizard-server
description: PeSIT Wizard Server - PeSIT file transfer server (standalone mode)
type: application
version: 1.2.1
appVersion: "1.2.1"
keywords:
  - pesitwizard
  - pesit
  - file-transfer
  - server
maintainers:
  - name: PeSIT Wizard Team
