#!/bin/bash
# Configure Connect:Express SSL/TLS parameters
# This script sets up SSL parameter tables for secure PeSIT connections

set -e

# Source CX profile
. $TOM_DIR/profile

echo "==========================================="
echo "  Connect:Express SSL Configuration"
echo "==========================================="

# Check if certificates exist
CERT_DIR="/app/certs"
if [ ! -d "$CERT_DIR" ]; then
    echo "WARNING: Certificate directory $CERT_DIR not found"
    echo "SSL configuration will be skipped"
    exit 0
fi

# Check for required certificate files
CA_CERT="$CERT_DIR/ca-cert.pem"
SERVER_CERT="$CERT_DIR/cx-server-cert.pem"
SERVER_KEY="$CERT_DIR/cx-server-key.pem"
CLIENT_CERT="$CERT_DIR/cx-client-cert.pem"
CLIENT_KEY="$CERT_DIR/cx-client-key.pem"

if [ ! -f "$CA_CERT" ]; then
    echo "WARNING: CA certificate not found at $CA_CERT"
    echo "SSL configuration will be skipped"
    exit 0
fi

echo "Certificates found:"
echo "  CA cert: $CA_CERT"
[ -f "$SERVER_CERT" ] && echo "  Server cert: $SERVER_CERT"
[ -f "$CLIENT_CERT" ] && echo "  Client cert: $CLIENT_CERT"

# Create CX SSL directory if it doesn't exist
CX_SSL_DIR="$TOM_DIR/ssl"
mkdir -p "$CX_SSL_DIR"

# Copy certificates to CX SSL directory
echo ""
echo "Copying certificates to CX SSL directory..."
cp "$CA_CERT" "$CX_SSL_DIR/ca-cert.pem"
[ -f "$SERVER_CERT" ] && cp "$SERVER_CERT" "$CX_SSL_DIR/server-cert.pem"
[ -f "$SERVER_KEY" ] && cp "$SERVER_KEY" "$CX_SSL_DIR/server-key.pem"
[ -f "$CLIENT_CERT" ] && cp "$CLIENT_CERT" "$CX_SSL_DIR/client-cert.pem"
[ -f "$CLIENT_KEY" ] && cp "$CLIENT_KEY" "$CX_SSL_DIR/client-key.pem"

# Set proper permissions
chmod 600 "$CX_SSL_DIR"/*.pem 2>/dev/null || true

echo ""
echo "Configuring SSL parameter table SSLPARM1 (Server mode - accept TLS connections)..."
# SSLPARM for server mode (CX receiving TLS connections from PW Client)
# NATURE=S indicates SSL/TLS
# VERIFY=0 = no client cert required (server-only auth)
# VERIFY=1 = request client cert (optional)
# VERIFY=2 = require client cert (mTLS)
$TOM_DIR/config/tom_prm SSLPARM \
    "NAME=SSLPARM1,STATE=E,CERTFILE=$CX_SSL_DIR/server-cert.pem,KEYFILE=$CX_SSL_DIR/server-key.pem,CAFILE=$CX_SSL_DIR/ca-cert.pem,VERIFY=0,PROTOCOL=TLSv1.2,CIPHERS=HIGH:!aNULL:!MD5,MODE=REPLACE" 2>/dev/null || \
$TOM_DIR/config/tom_prm SSLPARM \
    "NAME=SSLPARM1,STATE=E,MODE=REPLACE" 2>/dev/null || \
echo "  Note: tom_prm SSLPARM may not be supported in this CX version"

echo ""
echo "Configuring SSL parameter table SSLPARM2 (Client mode - initiate TLS connections)..."
# SSLPARM for client mode (CX connecting to PW Server via TLS)
$TOM_DIR/config/tom_prm SSLPARM \
    "NAME=SSLPARM2,STATE=E,CERTFILE=$CX_SSL_DIR/client-cert.pem,KEYFILE=$CX_SSL_DIR/client-key.pem,CAFILE=$CX_SSL_DIR/ca-cert.pem,VERIFY=1,PROTOCOL=TLSv1.2,CIPHERS=HIGH:!aNULL:!MD5,MODE=REPLACE" 2>/dev/null || \
$TOM_DIR/config/tom_prm SSLPARM \
    "NAME=SSLPARM2,STATE=E,MODE=REPLACE" 2>/dev/null || \
echo "  Note: tom_prm SSLPARM may not be supported in this CX version"

# Alternative: Create SSL config file directly if tom_prm doesn't support SSLPARM
SSL_CONFIG="$TOM_DIR/config/sslparm"
if [ ! -f "$SSL_CONFIG" ] || ! grep -q "SSLPARM1" "$SSL_CONFIG" 2>/dev/null; then
    echo ""
    echo "Creating SSL parameter file directly..."
    cat > "$SSL_CONFIG" << EOF
# SSL Parameter Tables for Connect:Express
# Generated by setup-ssl.sh

# SSLPARM1: Server mode (accept TLS connections)
SSLPARM1:
  CERTFILE=$CX_SSL_DIR/server-cert.pem
  KEYFILE=$CX_SSL_DIR/server-key.pem
  CAFILE=$CX_SSL_DIR/ca-cert.pem
  VERIFY=0
  PROTOCOL=TLSv1.2

# SSLPARM2: Client mode with mTLS (initiate TLS connections)
SSLPARM2:
  CERTFILE=$CX_SSL_DIR/client-cert.pem
  KEYFILE=$CX_SSL_DIR/client-key.pem
  CAFILE=$CX_SSL_DIR/ca-cert.pem
  VERIFY=1
  PROTOCOL=TLSv1.2
EOF
    echo "  Created $SSL_CONFIG"
fi

echo ""
echo "SSL configuration complete."
echo ""
echo "To enable TLS for partners, use NATURE=S and SSLPARM=SSLPARM1 or SSLPARM2"
echo "Example:"
echo "  tom_prm PARTNER 'NAME=PWSRV01,...,NATURE=S,SSLPARM=SSLPARM1,...'"
